management.statsd.metrics.export.enabled=true
management.statsd.metrics.export.flavor=etsy
management.statsd.metrics.export.host=localhost
management.statsd.metrics.export.port=8125
management.endpoints.web.exposure.include=health,info,metrics
